<!-- header.inc -->
<?php
ini_set('display_errors',1);
error_reporting(E_ALL);
?>
<!DOCTYPE html>
<html lang="en">

<head>
	<title>Pets Victoria</title>
	<meta charset=utf-8>
	<link rel="stylesheet" href="stylesheet.css">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Permanent+Marker">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Poetsen+One&display=swap">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Ysabeau+SC:wght@1..1000&display=swap">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined">
	<script src="menu.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<!-- end of header.inc -->