<!-- nav.inc -->
<header>
	<div class="search">
		<input type="text" placeholder="Search">
	</div>
	<div class="logo">
		<img src="images/images/logo.png" alt="Logo">
	</div>
	<div class="Icon">
	   <span class="material-symbols-outlined">search</span>
    </div>
	<nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
        </div>
        <ul class="nav navbar-nav">
          <li class="active"><a href="index.php">Home</a></li>
          <li><a href="pets.php">Pets</a></li>
          <li><a href="add.php">Add</a></li>
		  <li><a href="gallery.php">Gallery</a></li>
		  <li><a href="login.php">Login</a></li>
		  <li><a href="register.php">Register</a></li>
        </ul>
       </div>
    </nav>
	
   </header>
<!-- end of nav.inc -->