<!-- nav.inc -->
<header>
	<div class="search">
		<input type="text" placeholder="Search">
	</div>
	<div class="logo">
		<img src="images/images/logo.png" alt="Logo">
	</div>
	<div class="Icon">
	   <span class="material-symbols-outlined">search</span>
    </div>
	<div class="dropdown">
		<form>
			<select id="menu" onchange=doMenu();>
				<option value="">Select an Option...</option>
				<option value="index.php">Index</option>
				<option value="pets.php">Pets</option>
				<option value="add.php">Add</option>
				<option value="login.php">Login</option>
				<option value="logout.php">Logout</option>
				<option value="register.php">Register</option>
			</select>
		</form>
	</div>
	
   </header>
<!-- end of nav.inc -->