<!-- header.inc -->
<!DOCTYPE html>
<html lang="en">

<head>
	<title>Pets Victoria</title>
	<meta charset=utf-8>
	<link rel="stylesheet" href="stylesheet.css">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Permanent+Marker">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Poetsen+One&display=swap">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Ysabeau+SC:wght@1..1000&display=swap">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined">
	<script src="menu.js"></script>
</head>
<!-- end of header.inc -->