<!-- header.inc -->
<?php
ini_set('display_errors',1);
error_reporting(E_ALL);
?>
<!DOCTYPE html>
<html lang="en">

<head>
	<title>Pets Victoria</title>
	<meta charset=utf-8>
	<link rel="stylesheet" href="stylesheet.css">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Permanent+Marker">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Poetsen+One&display=swap">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Ysabeau+SC:wght@1..1000&display=swap">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined">
	<script src="menu.js"></script>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<!-- end of header.inc -->